name: Build and push image to ECR

on: push

env:
  EC2_HOST: 18.136.101.148
  SSH_USER: ubuntu
  
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 16.x]
        
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name : npm install
        run: npm ci
      - name : tests
        run: |
          npm test
          npm run test:e2e
  
  build:
    name: Build Image
    runs-on: ubuntu-latest
    needs: tests
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 927190304276.dkr.ecr.ap-southeast-1.amazonaws.com
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: 927190304276.dkr.ecr.ap-southeast-1.amazonaws.com
        ECR_REPOSITORY: ecr-for-ec2
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Configure SSH
      run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          cat >>~/.ssh/config <<END
          Host ec2
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github-actions-key
            StrictHostKeyChecking no
          END
          
      env:
          SSH_HOST: ${{ env.EC2_HOST }}
          SSH_USER: ${{ env.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo apt-get update
            sudo apt install apt-transport-https ca-certificates curl software-properties-common -y
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt update
            sudo apt install docker-ce -y
            docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
