name: Build and push image to ECR

on: push

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  SSH_AUTH_SOCK_DEBUG: "true"
  KEY_PATH: ${{ github.workspace }}/key_dev.pem

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 16.x]
        
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
#       - name : npm install
#         run: npm ci
#       - name : tests
#         run: |
#           npm test
#           npm run test:e2e
  
  build:
    name: Build Image
    runs-on: ubuntu-latest
    needs: tests
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 927190304276.dkr.ecr.ap-southeast-1.amazonaws.com
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: 927190304276.dkr.ecr.ap-southeast-1.amazonaws.com
        ECR_REPOSITORY: ecr-for-ec2
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
#     - name: Get EC2 public IP address
#       run: |
#          sudo -i
#          sudo apt update
#          sudo apt install ssh -y
#          pwd
#          sudo mkdir /home/runner/.ssh
#          sudo chmod 600 /home/runner/.ssh
#          sudo cd /home/runner/.ssh
#          sudo ls -la
#          sudo ssh-keygen -t rsa -q -P "" -y
#          sudo chmod 400 /home/runner/.ssh/id_rsa.pub
#          #        cd ../../../
         
    - name: Check out code
      uses: actions/checkout@v2
    - name: install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install awscli
        aws --version
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set default.region ap-south-1
        
    - name: SSH to EC2 instance && install docker service && pull docker image from ECR
      uses: appleboy/ssh-action@master
      with:
       host: ${{ secrets.EC2_HOST }}
       username: ubuntu
       key: ${{ secrets.SSH_PRIVATE_KEY }}
       script: |
            cd ../ && chmod 400 ${{ github.workspace }}/key_dev.pem
            ssh -i ${{ github.workspace }}/key_dev.pem ubuntu@54.179.169.236
            sudo docker pull 927190304276.dkr.ecr.ap-southeast-1.amazonaws.com/ecr-for-ec2:${{ github.sha }}
            sudo docker images
