name: Build and push image to ECR

on: push
env:
  REGION: ap-southeast-1
  ECR_REGISTRY: 927190304276.dkr.ecr.ap-southeast-1.amazonaws.com
  ECR_REPO: ecr-for-ec2
  
jobs:
  tests:
    runs-on: ubuntu-latest  
    strategy:
      matrix:
        node-version: [18.x, 16.x]
  
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name : npm install
        run: npm ci
      - name : tests
        run: |
           npm test
           npm run test:e2e
           
  build:
    name: Build Image
    runs-on: ubuntu-latest
    needs: tests
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Login to ECR
      run: |
        aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: 927190304276.dkr.ecr.ap-southeast-1.amazonaws.com
        ECR_REPOSITORY: ecr-for-ec2
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
         
    - name: Check out code
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
        
    - name: SSH to EC2 instance && install docker service && pull docker image from ECR
      uses: appleboy/ssh-action@master
      with:
       host: ${{ secrets.EC2_HOST }}
       username: ubuntu
       key: ${{ secrets.SSH_PRIVATE_KEY }}
       script: |
        pwd
        aws configure 
        sudo apt update -y
        sudo docker login -u AWS -p $(aws ecr get-login-password --region $REGION) https://$ECR_REGISTRY/$ECR_REPO
        sudo docker pull $ECR_REGISTRY/$ECR_REPO:${{ github.sha }}
        sudo docker images
